
    #mysql
    #mybatis-plus
    #mybatis-plus.mapper-locations=classpath:com/mht/springbootmybatisplus/mapper/xml/*.xml
    #mybatis-plus.type-aliases-package=com.dhh.bookkeeper.entry
    #mybatis-plus.configuration.map-underscore-to-camel-case: true


  server:
    port: 8084
  spring:
    datasource:
      url: jdbc:mysql://106.15.229.91:3306/score-indicator?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: Qq123123
      driver-class-name: com.mysql.cj.jdbc.Driver
  mconfig:
    swagger-ui-open: true